name: release
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3
      - run: scripts/update.sh
      - name: check for changes to commit
        run: >
          git config user.email "bradrf+brewtap@bitpony.com"
          git config user.name "BitPony Tap"
          if git status --porcelain=v1 | grep -q '^ M '; then
            git commit -m "`git diff`";
          else
            echo 'Nothing to change';
          fi
