name: release
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: scripts/update.sh
      - name: check for changes to commit
        run: |
          set -x
          if [ git status | grep -q '^ M ' ]; then
            git commit -m "`git diff`"
          else
            echo 'Nothing to change'
          fi